name: "Podcast Generator"
Author: "Richard Raynor"
Desription: "Generates a feed for a podcast from a YAML file"
runs:
  Using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    Desription: the commiter's email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    Desription: the commiter's name
    required: true
    default: ${{ github.actor}}
